### ISSUE TITLE
[Bug] Docker is not working, giving me 404 

### ISSUE THREAD

**Issue by echo-saurav** [mcndt/noteshare.space#15]
I ran `docker-compose up --build` , everything seems to start correctly but when i go `http:ip:5000 ` i get `404 page not found`

**Comment by mcndt** [comment]
Hi echo-saurav,

On my local machine (Windows, docker engine running on WSL2), I can run `docker-compose up --build` and subsequently reach the web app on `http://localhost:5000` as well as make POST requests to the API used by the plugin.

In the production environment, I run a slightly modified version of the same docker-compose file in this repo and that works too. 

Can you give me more information about the environment you're running docker compose in?

**Comment by echo-saurav** [comment]
I am running it on arch linux, i can access traefik, it shows no error

**Comment by mcndt** [comment]
I believe this rule in the docker compose file is the problem:

```yaml
(...)
frontend:
    (...)
    labels:
      (...)
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"  # 
```

`localhost` is specific to Windows iirc. For Linux-based systems, try changing this to 0.0.0.0 for local operation.

If you're hosting on a server, you should change this to either the IP address you are connecting with, or the (sub)domain if you use DNS. (e.g. on production I use `Host('noteshare.space')`.

This routing rule is present in every service (`backend`, `frontend`, `grafana`) so don't forget to adapt it for every service according to your needs.

Let me know if that helps!

**Comment by echo-saurav** [comment]
I change it to my actual local ip, now its working , thanks!
but one thing when i try to copy url, its shows `htttp:localhost/note/...`, can it be change to the actual ip?

**Comment by mcndt** [comment]
Glad that worked!

You can configure this similarly in the docker compose file:

```yml
backend:
    (...)
    environment:
      - DATABASE_URL=file:/database/db.sqlite
      - FRONTEND_URL=http://localhost:5000
      - CLEANUP_INTERVAL_SECONDS=600
      - NODE_ENV=production
      # Rate limit for uploading notes
      - POST_LIMIT_WINDOW_SECONDS=86400
      - POST_LIMIT=50
      # Rate limit for downloading notes
      - GET_LIMIT_WINDOW_SECONDS=60
      - GET_LIMIT=20
```

You can change the `FRONTEND_URL` variable to whatever base URL you want to host the frontend at. Here you can also configure other settings. the frontend service also has some settings you can configure in this way, such as the branding in the top-left corner of the website.
